Souped_Up/Controllers/DishController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using Souped_Up.Data;
using Souped_Up.Models;
using Souped_Up.Services.Implementations;
using Souped_Up.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Souped_Up.Controllers
{
    public class DishController : Controller
    {
        //readonly IDishRepo dishRepo;
        private IDishService DishService { get; set; }
        private IIngredientService IngredientService { get; set; }
        private ITagService TagService { get; set; }
        public DishController(IDishService dishService, ITagService tagService, IIngredientService ingredientService)
        {
            DishService = dishService;
            TagService = tagService;
            IngredientService = ingredientService;
        }
        // GET: Dish
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var model = DishService.GetUserDishes(userId);

            return View(model);
        }
    
        public ActionResult ListDish(DishViewListItemModel model)
        {
            return PartialView(model);
        }
        //GET
        public ActionResult Create()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());

            var ingredients = IngredientService.GetUserIngredientSelectList(userId);
            var tags = TagService.GetUserTagSelectList(userId);
            DishViewCreateModel model = new DishViewCreateModel();
            model.IngredientData = ingredients.ToList();
            model.TagData = tags.ToList();
            return View(model);

        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DishViewCreateModel model)
        {
            if (!ModelState.IsValid) return View(model);
            model.UserId = Guid.Parse(User.Identity.GetUserId());

            if (DishService.Create(model))
            {
                TempData["SaveResult"] = "Your dish was created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Dish could not be created.");
            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var dish = DishService.GetDetails(id);
            return View(dish);
        }
        public ActionResult Edit(int id)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var model = DishService.GetEditById(id);
            var ingredients = IngredientService.GetUserIngredientSelectList(userId);
            var tags = TagService.GetUserTagSelectList(userId);
            
            model.IngredientData = ingredients.ToList();
            model.TagData = tags.ToList();
            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, DishViewEditModel model)
        {
            if (!ModelState.IsValid) return View(model);

            if (DishService.Update(model))
            {
                TempData["SaveResult"] = "Your dish was updated.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Dish could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var dish = DishService.GetDetails(id);
            return View(dish);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteDish(int id)
        {
            DishService.Delete(id);

            TempData["SaveResult"] = "Your dish was deleted";

            return RedirectToAction("Index");
        }
    }
}

Souped_Up/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Souped_Up.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Souped_Up/Controllers/IngredientController.cs
using Microsoft.AspNet.Identity;
using Souped_Up.Models;
using Souped_Up.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Souped_Up.Controllers
{
    public class IngredientController : Controller
    {
        //readonly IIngredientRepo ingredientRepo;
        private IIngredientService IngredientService { get; set; }
        public IngredientController(IIngredientService ingredientService)
        {
            IngredientService = ingredientService;
        }
        // GET: Ingredient
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var model = IngredientService.GetUserIngredients(userId);

            return View(model);
        }
        public ActionResult ListIngredient(IngredientViewListItemModel model)
        {
            return PartialView(model);
        }
        //GET
        public ActionResult Create()
        {
            IngredientViewCreateModel model = new IngredientViewCreateModel();
            return View(model);
        }
        
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IngredientViewCreateModel model)
        {
            if (!ModelState.IsValid) return View(model);
            model.UserId = Guid.Parse(User.Identity.GetUserId());

            if (IngredientService.Create(model))
            {
                TempData["SaveResult"] = "Your ingredient was created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Ingredient could not be created.");
            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var meal = IngredientService.GetDetails(id);
            return View(meal);
        }
        public ActionResult Edit(int id)
        {
            var model = IngredientService.GetEditById(id);
            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IngredientViewEditModel model)
        {
            if (!ModelState.IsValid) return View(model);

            if (IngredientService.Update(model))
            {
                TempData["SaveResult"] = "Your ingredient was updated.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Ingredient could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var ingredient = IngredientService.GetDetails(id);
            return View(ingredient);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteIngredient(int id)
        {
            IngredientService.Delete(id);

            TempData["SaveResult"] = "Your ingredient was deleted";

            return RedirectToAction("Index");
        }

    }
}

Souped_Up/Controllers/MealController.cs
using Microsoft.AspNet.Identity;
using Souped_Up.Data;
using Souped_Up.Models;
using Souped_Up.Repos.Interfaces;
using Souped_Up.Services.Implementations;
using Souped_Up.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Souped_Up.Controllers
{
    [Authorize]
    public class MealController : Controller
    {
        // readonly IMealRepo mealRepo;
        private IMealService MealService { get; set; }
        private IDishService DishService { get; set; }
        private ITagService TagService { get; set; }
        public MealController(IMealService mealService, IDishService dishService, ITagService tagService)
        {
            MealService = mealService;
            DishService = dishService;
            TagService = tagService;
        }
        // GET: Meal
        public ActionResult Index()
        {


            var userId = Guid.Parse(User.Identity.GetUserId());
            var model = MealService.GetUserMeals(userId);

            return View(model);
        }
        public ActionResult ListMeal(MealViewListItemModel model)
        {
            return PartialView(model);
        }

        //GET
        public ActionResult Create()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var dishes = DishService.GetUserDishSelectList(userId);
            var tags = TagService.GetUserTagSelectList(userId);
            MealViewCreateModel model = new MealViewCreateModel();
            model.DishData = dishes.ToList();
            model.TagData = tags.ToList();
            return View(model);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MealViewCreateModel model)
        {
            if (!ModelState.IsValid) return View(model);
            model.UserId = Guid.Parse(User.Identity.GetUserId());

            if (MealService.Create(model))
            {
                TempData["SaveResult"] = "Your meal was created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Meal could not be created.");
            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var meal = MealService.GetDetails(id);
            return View(meal);
        }

        public ActionResult Edit(int id)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var model = MealService.GetEditById(id);
            var dishes = DishService.GetUserDishSelectList(userId);
            var tags = TagService.GetUserTagSelectList(userId);

            model.DishData = dishes.ToList();
            model.TagData = tags.ToList();
            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MealViewEditModel model)
        {
            if (!ModelState.IsValid) return View(model);

            MealService.Update(model);
            TempData["SaveResult"] = "Your meal was updated.";
            return RedirectToAction("Index");

        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var model = MealService.GetDetails(id);
            return View(model);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteMeal(int id)
        {
            MealService.Delete(id);

            TempData["SaveResult"] = "Your meal was deleted";

            return RedirectToAction("Index");
        }
        public JsonResult GetDishes()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var dishes = DishService.GetUserDishes(userId);

            return Json(dishes, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetTags()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var tags = TagService.GetUserTags(userId);

            return Json(tags, JsonRequestBehavior.AllowGet);
        }
    }
}

Souped_Up/Controllers/TagController.cs
using Microsoft.AspNet.Identity;
using Souped_Up.Models;
using Souped_Up.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Souped_Up.Controllers
{
    [Authorize]
    public class TagController : Controller
    {
        //readonly ITagRepo tagRepo
        private ITagService TagService { get; set; }
        public TagController(ITagService tagService)
        {
            TagService = tagService;
        }
        // GET: Tag
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var model =TagService.GetUserTags(userId);

            return View(model);
        }
        public ActionResult ListTag(TagViewListItemModel model)
        {
            return PartialView(model);
        }
        //GET
        public ActionResult Create()
        {
            TagViewCreateModel model = new TagViewCreateModel();
            return View(model);
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TagViewCreateModel model)
        {
            if (!ModelState.IsValid) return View(model);
            model.UserId = Guid.Parse(User.Identity.GetUserId());

            if (TagService.Create(model))
            {
                TempData["SaveResult"] = "Your tag was created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Tag could not be created.");
            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var tag = TagService.GetDetails(id);
            return View(tag);
        }

        public ActionResult Edit(int id)
        {
            var model = TagService.GetEditById(id);
            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TagViewEditModel model)
        {
            if (!ModelState.IsValid) return View(model);

            if (TagService.Update(model))
            {
                TempData["SaveResult"] = "Your tag was updated.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Tag could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var tag = TagService.GetDetails(id);
            return View(tag);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteTag(int id)
        {
            TagService.Delete(id);

            TempData["SaveResult"] = "Your tag was deleted";

            return RedirectToAction("Index");
        }

    }
}

Souped_Up/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    Souped-Up is a meal planning app created as part of a Software Development BootCamp with the ElevenFifty Academy. The inspiration for this app came from the daily struggle of answering "What's for dinner?".

    This App allows users to create a repository for their own meals including dishes for the meal(entree, sidedish, dessert, etc) as well as the ingredients necessary.To make this app more customizable, users are able to create their own categories for Meals and Dishes.
</p>

Souped_Up/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>Have an idea on how we can improve this app? Please let us know!</h3>


<address>
    <strong>Email Us:</strong>   <a href="mailto:kirstin.oaldon@gmail.com">kirstin.oaldon@gmail.com</a><br />
</address>

Souped_Up/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<style>
    .jumbotron {
        background-image: url(../../Content/Assets/background.jpg);
        background-size: cover;
    }

        .jumbotron h1 {
            font-family: 'Freestyle Script';
            font-size: 150px;
            position: relative;
            left: 575px;
            top: 10px;
        }

        .jumbotron p {
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            font-size: 20px;
            position: relative;
            left: 675px;
        }

    .card-img-top {
        width: 250px;
        height: 150px;
    }
</style>

<div class="jumbotron">
    <h1>Souped-Up</h1>
    <p class="lead">Meal planning made easy.</p>
</div>


<div class="card-deck ">
    <div class="col-md-6">
        <div class="card text-center" style="width:275px">
            <img src="~/Content/Assets/Meal.jpg" class="card-img-top" alt="Meal Image" />
            <div class="card-body">
                <h4 class="card-title">View your Meals</h4>
                <p class="card-text">Create, Edit, Delete, or find more information about your meals!</p>
                @Html.ActionLink("View Meals", "Index", "Meal", null, new { @class = "btn btn-primary btn-large" })
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card text-center" style="width:275px">
            <img src="~/Content/Assets/Dish.jpg" class="card-img-top" alt="Dish Image" />
            <div class="card-body">
                <h4 class="card-title">View your Dishes</h4>
                <p class="card-text">Create, Edit, Delete, or find more information about your dishes!</p>
                @Html.ActionLink("View Dishes", "Index", "Dish", null, new { @class = "btn btn-primary btn-large" })
            </div>
        </div>
    </div>
    <br />

    <div class="col-md-6">
        <div class="card text-center" style="width:275px">
            <img src="~/Content/Assets/Ingredient.jpg" class="card-img-top" alt="Ingredient Image" />
            <div class="card-body">
                <h4 class="card-title">View your Ingredients</h4>
                <p class="card-text">Create, Edit, Delete, or find more information about your ingredients!</p>
                @Html.ActionLink("View Ingredients", "Index", "Ingredient", null, new { @class = "btn btn-primary btn-large" })
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card text-center" style="width:275px">
            <img src="~/Content/Assets/Tags.jpg" class="card-img-top" alt="Tag Image" />
            <div class="card-body">
                <h4 class="card-title">View your Tags</h4>
                <p class="card-text">Create, Edit, Delete, or find more information about your tags!</p>
                @Html.ActionLink("View Tags", "Index", "Tag", null, new { @class = "btn btn-primary btn-large" })
            </div>
        </div>
    </div>
</div>